name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Cache Dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn

      - name: Run lint
        run: yarn eslint .
